baseURL = 'https://pop-web.github.io/'
languageCode = 'ja'
title = 'POPWEB'
theme = 'PaperMod'
hasCJKLanguage = true

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true


[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "記事一覧"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "カテゴリー"
  url = "/categories/"
  weight = 20

[[menu.main]]
  name = "アーカイブ"
  url = "/archives/"
  weight = 30

[[menu.main]]
  name = "検索"
  url = "/search/"
  weight = 40
